#pragma once

#include "mouthAngry.h"
#include "mouthBitmap.h"
#include "mouthDefault.h"
#include "mouthUp.h"
#include "mouthDown.h"
#include "mouthDrooling.h"
#include "mouthEh.h"
#include "mouthLower.h"
#include "mouthPout.h"
#include "mouthShock.h"
#include "mouthSmall.h"
#include "mouthViseme.h"
#include "mouthWah.h"
#include "mouthWorry.h"
